{
 "title": "Railgun Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "address_0",
    "query": "0x65D54eEb3bebe4a99c620631e6744694C98b3262"
   },
   {
    "name": "address_1",
    "query": "0xd75D689fdf6EB7b362119e29cA29b0a2869660aa"
   }
  ]
 },
 "panels": [
  {
   "title": "Ethereum Gas Balance $address_0",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gas_token_balance{chain_type=\"EVM\", chain_id=\"Ethereum Mainnet\", address=\"$address_0\", derivation_index=\"0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Polygon Gas Balance $address_0",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gas_token_balance{chain_type=\"EVM\", chain_id=\"Polygon Mainnet\", address=\"$address_0\", derivation_index=\"0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BNB Gas Balance $address_0",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gas_token_balance{chain_type=\"EVM\", chain_id=\"Binance Smart Chain\", address=\"$address_0\", derivation_index=\"0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Goerli Gas Balance $address_0",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gas_token_balance{chain_type=\"EVM\", chain_id=\"Ethereum Goerli\", address=\"$address_0\", derivation_index=\"0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Mumbai Gas Balance $address_0",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gas_token_balance{chain_type=\"EVM\", chain_id=\"Polygon Mumbai Testnet\", address=\"$address_0\", derivation_index=\"0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ethereum Gas Balance $address_1",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gas_token_balance{chain_type=\"EVM\", chain_id=\"Ethereum Mainnet\", address=\"$address_1\", derivation_index=\"1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Polygon Gas Balance $address_1",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 5, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gas_token_balance{chain_type=\"EVM\", chain_id=\"Polygon Mainnet\", address=\"$address_1\", derivation_index=\"1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BNB Gas Balance $address_1",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gas_token_balance{chain_type=\"EVM\", chain_id=\"Binance Smart Chain\", address=\"$address_1\", derivation_index=\"1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Goerli Gas Balance $address_1",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gas_token_balance{chain_type=\"EVM\", chain_id=\"Ethereum Goerli\", address=\"$address_1\", derivation_index=\"1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Mumbai Gas Balance $address_1",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gas_token_balance{chain_type=\"EVM\", chain_id=\"Polygon Mumbai Testnet\", address=\"$address_1\", derivation_index=\"1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shielded USDT Balance - Ethereum",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "shielded_token_balance{chain_type=\"EVM\", chain_id=\"Ethereum Mainnet\", token_address=\"0xdac17f958d2ee523a2206206994597c13d831ec7\"}",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Shielded WETH Balance - Ethereum",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 5, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "shielded_token_balance{chain_type=\"EVM\", chain_id=\"Ethereum Mainnet\", token_address=\"0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2\"}",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Shielded WBTC Balance - Ethereum",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "shielded_token_balance{chain_type=\"EVM\", chain_id=\"Ethereum Mainnet\", token_address=\"0x2260fac5e5542a773aa44fbcfedf7c193bc2c599\"}",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Shielded DAI Balance - Ethereum",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "shielded_token_balance{chain_type=\"EVM\", chain_id=\"Ethereum Mainnet\", token_address=\"0x6B175474E89094C44Da98b954EedeAC495271d0F\"}",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Shielded USDC Balance - Ethereum",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "shielded_token_balance{chain_type=\"EVM\", chain_id=\"Ethereum Mainnet\", token_address=\"0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48\"}",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Shielded RAI Balance - Ethereum",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "shielded_token_balance{chain_type=\"EVM\", chain_id=\"Ethereum Mainnet\", token_address=\"0x03ab458634910aad20ef5f1c8ee96f1d6ac54919\"}",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Shielded RAIL Balance - Ethereum",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 5, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "shielded_token_balance{chain_type=\"EVM\", chain_id=\"Ethereum Mainnet\", token_address=\"0xe76C6c83af64e4C60245D8C7dE953DF673a7A33D\"}",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Shielded FRAX Balance - Ethereum",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "shielded_token_balance{chain_type=\"EVM\", chain_id=\"Ethereum Mainnet\", token_address=\"0x853d955acef822db058eb8505911ed77f175b99e\"}",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Shielded FEI Balance - Ethereum",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "shielded_token_balance{chain_type=\"EVM\", chain_id=\"Ethereum Mainnet\", token_address=\"0x956F47F50A910163D8BF957Cf5846D573E7f87CA\"}",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Shielded RENDOGE Balance - Ethereum",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "shielded_token_balance{chain_type=\"EVM\", chain_id=\"Ethereum Mainnet\", token_address=\"0x3832d2f059e55934220881f831be501d180671a7\"}",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Shielded REN Balance - Ethereum",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "shielded_token_balance{chain_type=\"EVM\", chain_id=\"Ethereum Mainnet\", token_address=\"0x408e41876cccdc0f92210600ef50372656052a38\"}",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Shielded RENFIL Balance - Ethereum",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 5, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "shielded_token_balance{chain_type=\"EVM\", chain_id=\"Ethereum Mainnet\", token_address=\"0xd5147bc8e386d91cc5dbe72099dac6c9b99276f5\"}",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Shielded RENBTC Balance - Ethereum",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "shielded_token_balance{chain_type=\"EVM\", chain_id=\"Ethereum Mainnet\", token_address=\"0xeb4c2781e4eba804ce9a9803c67d0893436bb27d\"}",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Shielded WETH Balance - Goerli",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "shielded_token_balance{chain_type=\"EVM\", chain_id=\"Ethereum Goerli\", token_address=\"0xb4fbf271143f4fbf7b91a5ded31805e42b2208d6\"}",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Shielded WBNB Balance - BSC",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "shielded_token_balance{chain_type=\"EVM\", chain_id=\"Binance Smart Chain\", token_address=\"0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c\"}",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Shielded Balance WETH - Polygon",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "shielded_token_balance{chain_type=\"EVM\", chain_id=\"Polygon Mainnet\", token_address=\"0xA649325Aa7C5093d12D6F98EB4378deAe68CE23F\"}",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Shielded Balance  BUSD - BSC",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 5, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "shielded_token_balance{chain_type=\"EVM\", chain_id=\"Binance Smart Chain\", token_address=\"0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56\"}",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Shielded Balance CAKE - BSC",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "shielded_token_balance{chain_type=\"EVM\", chain_id=\"Binance Smart Chain\", token_address=\"0x0E09FaBB73Bd3Ade0a17ECC321fD13a19e81cE82\"}",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Shielded Balance USDC - BSC",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "shielded_token_balance{chain_type=\"EVM\", chain_id=\"Binance Smart Chain\", token_address=\"0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d\"}",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Shielded Balance BNB - Polygon",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "shielded_token_balance{chain_type=\"EVM\", chain_id=\"Polygon Mainnet\", token_address=\"0xA649325Aa7C5093d12D6F98EB4378deAe68CE23F\"}",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Shielded Balance USDC - Polygon",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "shielded_token_balance{chain_type=\"EVM\", chain_id=\"Polygon Mainnet\", token_address=\"0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174\"}",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Shielded Balance USDT - BSC",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 5, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "shielded_token_balance{chain_type=\"EVM\", chain_id=\"Binance Smart Chain\", token_address=\"0x55d398326f99059fF775485246999027B3197955\"}",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Shielded Balance  BUSD - BSC",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "shielded_token_balance{chain_type=\"EVM\", chain_id=\"Binance Smart Chain\", token_address=\"0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56\"}",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Shielded Balance DAI - Polygon",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "shielded_token_balance{chain_type=\"EVM\", chain_id=\"Polygon Mainnet\", token_address=\"0x8f3cf7ad23cd3cadbd9735aff958023239c6a063\"}",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Shielded Balance WMATIC - Polygon",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "shielded_token_balance{chain_type=\"EVM\", chain_id=\"Polygon Mainnet\", token_address=\"0x0d500b1d8e8ef31e21c99d1db9a6444d3adf1270\"}",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Shielded Balance WBTC - Polygon",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "shielded_token_balance{chain_type=\"EVM\", chain_id=\"Polygon Mainnet\", token_address=\"0x1BFD67037B42Cf73acF2047067bd4F2C47D9BfD6\"}",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Shielded Balance USDT - Polygon",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 5, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "shielded_token_balance{chain_type=\"EVM\", chain_id=\"Polygon Mainnet\", token_address=\"0xc2132D05D31c914a87C6611C10748AEb04B58e8F\"}",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Shielded Balance WMATIC - Polygon Mumbai",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "shielded_token_balance{chain_type=\"EVM\", chain_id=\"Polygon Mainnet\", token_address=\"0x9c3C9283D3e44854697Cd22D3Faa240Cfb032889\"}",
     "legendFormat": "__auto"
    },
    {}
   ]
  }
 ]
}